FROM mcr.microsoft.com/dotnet/sdk:6.0.405-alpine3.17 AS build

WORKDIR /app

COPY . .

WORKDIR /app
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0.13-alpine3.17 AS runtime

WORKDIR /app

COPY --from=build /app/out ./

CMD ["dotnet", "alpine317segfault.dll"]
