FROM mcr.microsoft.com/dotnet/sdk:6.0.405-alpine3.17 AS build

WORKDIR /app

COPY . .

RUN dotnet publish -c Release -o pub

FROM mcr.microsoft.com/dotnet/aspnet:6.0.13-alpine3.17

WORKDIR /app

COPY --from=build /app/pub ./

ENTRYPOINT ["dotnet", "alpine317segfault.dll"]
